name: Good Governance
favicon: null
layout_spectrum: 0.52023
typography_spectrum: 0.51248
title: Good Governance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b2b2b2'
    - '#8f9095'
    - '#566173'
    - '#0f1418'
    - '#414858'
  brandStrength: 0.9253003713674843
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
